"""xxx

Revision ID: edaaa0234e5c
Revises: 
Create Date: 2023-07-28 16:59:50.769410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaaa0234e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfermeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('Nregistro', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_local', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('sus', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_enfermeiro', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.String(length=1000), nullable=True),
    sa.Column('tempo_dose', sa.String(length=100), nullable=True),
    sa.Column('data_vencimento', sa.String(length=100), nullable=True),
    sa.Column('local_vacina', sa.String(length=100), nullable=True),
    sa.Column('disponivel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_enfermeiro'], ['enfermeiro.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacinacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_enfermeiro', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_estoque', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_enfermeiro'], ['enfermeiro.id'], ),
    sa.ForeignKeyConstraint(['id_estoque'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacinacao')
    op.drop_table('estoque')
    op.drop_table('usuario')
    op.drop_table('local')
    op.drop_table('enfermeiro')
    # ### end Alembic commands ###
